version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: ecommerce_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    volumes:
      - db_data:/var/lib/mysql
      - ./ecommerce.sql:/docker-entrypoint-initdb.d/1-schema.sql:ro
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -proot --silent"]
      interval: 5s
      timeout: 3s
      retries: 30

  app:
    build: .
    container_name: ecommerce_app
    environment:
      PORT: 5000
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: ecommerce
      SESSION_SECRET: your_secret_key
    depends_on:
      db:
        condition: service_healthy
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: node server.js

volumes:
  db_data:
